import type { QuestionBankCreateType } from "@/src/routes/questions/schema.js";

export const questions = [
  {
    category: "Production",
    title: "Purpose of Gypsum",
    question:
      "What is the primary purpose of adding gypsum during cement grinding?",
    difficultyLabel: "EASY",
    type: "CHOICE",
    explanation:
      "Gypsum controls the setting time of cement by regulating the hydration of C3A. Without gypsum, cement would set too rapidly.",
    estimatedTimeSeconds: 45,
    questionData: {
      context: "Cement Grinding Process",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 2,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "To control the setting time of cement",
        isCorrect: true,
        displayOrder: 0,
      },
      {
        choiceText: "To increase clinker production",
        isCorrect: false,
        displayOrder: 1,
      },
      {
        choiceText: "To reduce limestone consumption",
        isCorrect: false,
        displayOrder: 2,
      },
      {
        choiceText: "To improve kiln refractory life",
        isCorrect: false,
        displayOrder: 3,
      },
    ],
    jobTitles: ["Production Engineer", "Process Engineer", "CCR Operator"],
  },

  {
    category: "Production",
    title: "Clinker Quality",
    question: "A high free lime (f-CaO) value in clinker usually indicates:",
    difficultyLabel: "MEDIUM",
    type: "CHOICE",
    explanation:
      "High free lime generally means the clinker has been under-burned or insufficiently reacted inside the kiln.",
    estimatedTimeSeconds: 60,
    questionData: {
      context: "Clinker Production",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 4,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Incomplete clinker burning",
        isCorrect: true,
        displayOrder: 0,
      },
      {
        choiceText: "Excessive gypsum addition",
        isCorrect: false,
        displayOrder: 1,
      },
      {
        choiceText: "High cement fineness",
        isCorrect: false,
        displayOrder: 2,
      },
      {
        choiceText: "Low separator efficiency",
        isCorrect: false,
        displayOrder: 3,
      },
    ],
    jobTitles: ["Production Engineer", "Process Engineer", "Kiln Operator"],
  },

  {
    category: "Production",
    title: "Heat Consumption",
    question:
      "Which action is most effective in reducing the specific heat consumption of a modern dry-process cement plant?",
    difficultyLabel: "HARD",
    type: "CHOICE",
    explanation:
      "Improving preheater and precalciner efficiency increases heat recovery and lowers fuel consumption per ton of clinker.",
    estimatedTimeSeconds: 90,
    questionData: {
      context: "Energy Efficiency",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 6,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Improve preheater and precalciner efficiency",
        isCorrect: true,
        displayOrder: 0,
      },
      {
        choiceText: "Increase gypsum addition",
        isCorrect: false,
        displayOrder: 1,
      },
      {
        choiceText: "Reduce separator speed",
        isCorrect: false,
        displayOrder: 2,
      },
      {
        choiceText: "Decrease cement Blaine fineness",
        isCorrect: false,
        displayOrder: 3,
      },
    ],
    jobTitles: [
      "Senior Production Engineer",
      "Process Engineer",
      "CCR Operator",
    ],
  },

  {
    category: "Production",
    title: "Raw Material Proportioning",
    question:
      "Why is maintaining a stable raw mix chemistry important in cement manufacturing?",
    difficultyLabel: "MEDIUM",
    type: "CHOICE",
    explanation:
      "Stable raw mix chemistry ensures consistent clinker mineral composition, kiln stability, and cement quality.",
    estimatedTimeSeconds: 60,
    questionData: {
      context: "Raw Mix Control",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 4,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText:
          "It ensures consistent clinker quality and stable kiln operation",
        isCorrect: true,
        displayOrder: 0,
      },
      {
        choiceText: "It increases gypsum purity",
        isCorrect: false,
        displayOrder: 1,
      },
      {
        choiceText: "It reduces cement bag weight",
        isCorrect: false,
        displayOrder: 2,
      },
      {
        choiceText: "It eliminates separator maintenance",
        isCorrect: false,
        displayOrder: 3,
      },
    ],
    jobTitles: [
      "Production Engineer",
      "Quality Control Engineer",
      "Process Engineer",
    ],
  },

  {
    category: "Production",
    title: "Production Losses",
    question:
      "Which of the following has the greatest negative impact on overall cement plant productivity?",
    difficultyLabel: "MEDIUM",
    type: "CHOICE",
    explanation:
      "Unexpected equipment failures result in unplanned shutdowns, production losses, and higher maintenance costs.",
    estimatedTimeSeconds: 60,
    questionData: {
      context: "Plant Performance",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 4,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Unplanned equipment shutdowns",
        isCorrect: true,
        displayOrder: 0,
      },
      {
        choiceText: "Routine laboratory sampling",
        isCorrect: false,
        displayOrder: 1,
      },
      {
        choiceText: "Daily housekeeping",
        isCorrect: false,
        displayOrder: 2,
      },
      {
        choiceText: "Scheduled preventive maintenance",
        isCorrect: false,
        displayOrder: 3,
      },
    ],
    jobTitles: ["Production Engineer", "CCR Operator", "Process Engineer"],
  },
];

export const traineeSoftwareEngineerQuestions: QuestionBankCreateType[] = [
  {
    category: "JavaScript",
    title: "Block Scope with let",
    question:
      "A developer replaces var with let inside a loop. What is the primary benefit?",
    difficultyLabel: "EASY",
    type: "CHOICE",
    explanation: "let is block-scoped, reducing accidental leakage.",
    estimatedTimeSeconds: 45,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 2,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Block-scoped variables",
        displayOrder: 0,

        isCorrect: true,
      },
      {
        choiceText: "Automatic deep immutability",
        displayOrder: 0,

        isCorrect: false,
      },
      {
        choiceText: "Faster execution in all engines",
        displayOrder: 0,

        isCorrect: false,
      },
      {
        choiceText: "Variables become global",
        displayOrder: 0,

        isCorrect: false,
      },
    ],
    jobTitles: ["Trainee Software Engineer And Programmer"],
  },
  {
    category: "JavaScript",
    title: "Array.map",
    question: "Which method creates a new array by transforming every element?",
    difficultyLabel: "EASY",
    type: "CHOICE",
    explanation: "map returns a new transformed array.",
    estimatedTimeSeconds: 45,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 2,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "filter",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "reduce",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "map",
        displayOrder: 0,
        isCorrect: true,
      },
      {
        choiceText: "find",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: ["Trainee Software Engineer And Programmer"],
  },
  {
    category: "JavaScript",
    title: "Promise.all",
    question: "When does Promise.all reject?",
    difficultyLabel: "MEDIUM",
    type: "CHOICE",
    explanation: "It rejects immediately after the first rejection.",
    estimatedTimeSeconds: 60,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 4,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "When any promise rejects",
        displayOrder: 0,

        isCorrect: true,
      },
      {
        choiceText: "Only when all reject",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Never",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "After timeout",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: ["Trainee Software Engineer And Programmer"],
  },
  {
    category: "JavaScript",
    title: "Optional Chaining",
    question: "What does obj?.user?.name return when user is undefined?",
    difficultyLabel: "EASY",
    type: "CHOICE",
    explanation: "Optional chaining safely returns undefined.",
    estimatedTimeSeconds: 45,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 2,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Throws TypeError",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "undefined",
        displayOrder: 0,
        isCorrect: true,
      },
      {
        choiceText: "null",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "''",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: ["Trainee Software Engineer And Programmer"],
  },
  {
    category: "JavaScript",
    title: "Event Loop",
    question: "Which queue has higher priority after synchronous code?",
    difficultyLabel: "HARD",
    type: "CHOICE",
    explanation: "Microtasks run before macrotasks.",
    estimatedTimeSeconds: 90,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 6,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Timer queue",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Microtask queue",
        displayOrder: 0,
        isCorrect: true,
      },
      {
        choiceText: "Render queue",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Network queue",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: ["Trainee Software Engineer And Programmer"],
  },
  {
    category: "JavaScript",
    title: "Node Streams",
    question: "Why use streams for large files?",
    difficultyLabel: "MEDIUM",
    type: "CHOICE",
    explanation: "Streams process data incrementally.",
    estimatedTimeSeconds: 60,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 4,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Lower memory usage",
        displayOrder: 0,
        isCorrect: true,
      },
      {
        choiceText: "Automatic compression",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Faster CPU",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Parallel threads",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: ["Trainee Software Engineer And Programmer"],
  },
  {
    category: "JavaScript",
    title: "Closures",
    question:
      "A returned function accesses outer variables after return. This is enabled by?",
    difficultyLabel: "MEDIUM",
    type: "CHOICE",
    explanation: "Closures preserve lexical environment.",
    estimatedTimeSeconds: 60,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 4,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Inheritance",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Closure",
        displayOrder: 0,
        isCorrect: true,
      },
      {
        choiceText: "Prototype",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Currying",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: ["Trainee Software Engineer And Programmer"],
  },
  {
    category: "JavaScript",
    title: "this",
    question: "In an arrow function, this is determined by?",
    difficultyLabel: "MEDIUM",
    type: "CHOICE",
    explanation: "Arrow functions don't bind their own this.",
    estimatedTimeSeconds: 60,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 4,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Call site",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Lexical scope",
        displayOrder: 0,
        isCorrect: true,
      },
      {
        choiceText: "Global object always",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Prototype",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: ["Trainee Software Engineer And Programmer"],
  },
  {
    category: "JavaScript",
    title: "Object.freeze",
    question: "What does Object.freeze do?",
    difficultyLabel: "MEDIUM",
    type: "CHOICE",
    explanation: "Freeze is shallow.",
    estimatedTimeSeconds: 60,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 4,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Deletes properties",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Prevents modifications",
        displayOrder: 0,

        isCorrect: true,
      },
      {
        choiceText: "Makes deep immutable",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Changes prototype",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: ["Trainee Software Engineer And Programmer"],
  },
  {
    category: "JavaScript",
    title: "Debounce",
    question: "When is debouncing useful?",
    difficultyLabel: "MEDIUM",
    type: "CHOICE",
    explanation: "Debouncing limits rapid invocations.",
    estimatedTimeSeconds: 60,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 4,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Continuous animation",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Search input",
        displayOrder: 0,
        isCorrect: true,
      },
      {
        choiceText: "Sorting arrays",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "JSON parsing",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: ["Trainee Software Engineer And Programmer"],
  },
  {
    category: "JavaScript",
    title: "Block Scope with let #11",
    question:
      "A developer replaces var with let inside a loop. What is the primary benefit?",
    difficultyLabel: "EASY",
    type: "CHOICE",
    explanation: "let is block-scoped, reducing accidental leakage.",
    estimatedTimeSeconds: 45,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 2,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Block-scoped variables",
        displayOrder: 0,

        isCorrect: true,
      },
      {
        choiceText: "Automatic deep immutability",
        displayOrder: 0,

        isCorrect: false,
      },
      {
        choiceText: "Faster execution in all engines",
        displayOrder: 0,

        isCorrect: false,
      },
      {
        choiceText: "Variables become global",
        displayOrder: 0,

        isCorrect: false,
      },
    ],
    jobTitles: ["Software Engineer", "JavaScript Developer"],
  },
  {
    category: "JavaScript",
    title: "Array.map #12",
    question: "Which method creates a new array by transforming every element?",
    difficultyLabel: "EASY",
    type: "CHOICE",
    explanation: "map returns a new transformed array.",
    estimatedTimeSeconds: 45,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 2,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "filter",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "reduce",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "map",
        displayOrder: 0,
        isCorrect: true,
      },
      {
        choiceText: "find",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: ["Frontend Engineer", "React Developer"],
  },
  {
    category: "JavaScript",
    title: "Promise.all #13",
    question: "When does Promise.all reject?",
    difficultyLabel: "MEDIUM",
    type: "CHOICE",
    explanation: "It rejects immediately after the first rejection.",
    estimatedTimeSeconds: 60,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 4,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "When any promise rejects",
        displayOrder: 0,

        isCorrect: true,
      },
      {
        choiceText: "Only when all reject",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Never",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "After timeout",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: ["Backend Engineer", "Node.js Developer"],
  },
  {
    category: "JavaScript",
    title: "Optional Chaining #14",
    question: "What does obj?.user?.name return when user is undefined?",
    difficultyLabel: "EASY",
    type: "CHOICE",
    explanation: "Optional chaining safely returns undefined.",
    estimatedTimeSeconds: 45,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 2,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Throws TypeError",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "undefined",
        displayOrder: 0,
        isCorrect: true,
      },
      {
        choiceText: "null",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "''",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: ["Full Stack Developer", "TypeScript Developer"],
  },
  {
    category: "JavaScript",
    title: "Event Loop #15",
    question: "Which queue has higher priority after synchronous code?",
    difficultyLabel: "HARD",
    type: "CHOICE",
    explanation: "Microtasks run before macrotasks.",
    estimatedTimeSeconds: 90,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 6,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Timer queue",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Microtask queue",
        displayOrder: 0,
        isCorrect: true,
      },
      {
        choiceText: "Render queue",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Network queue",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: [
      "Software Engineer",
      "Frontend Engineer",
      "Full Stack Developer",
    ],
  },
  {
    category: "JavaScript",
    title: "Node Streams #16",
    question: "Why use streams for large files?",
    difficultyLabel: "MEDIUM",
    type: "CHOICE",
    explanation: "Streams process data incrementally.",
    estimatedTimeSeconds: 60,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 4,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Lower memory usage",
        displayOrder: 0,
        isCorrect: true,
      },
      {
        choiceText: "Automatic compression",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Faster CPU",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Parallel threads",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: ["Software Engineer", "JavaScript Developer"],
  },
  {
    category: "JavaScript",
    title: "Closures #17",
    question:
      "A returned function accesses outer variables after return. This is enabled by?",
    difficultyLabel: "MEDIUM",
    type: "CHOICE",
    explanation: "Closures preserve lexical environment.",
    estimatedTimeSeconds: 60,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 4,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Inheritance",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Closure",
        displayOrder: 0,
        isCorrect: true,
      },
      {
        choiceText: "Prototype",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Currying",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: ["Frontend Engineer", "React Developer"],
  },
  {
    category: "JavaScript",
    title: "this #18",
    question: "In an arrow function, this is determined by?",
    difficultyLabel: "MEDIUM",
    type: "CHOICE",
    explanation: "Arrow functions don't bind their own this.",
    estimatedTimeSeconds: 60,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 4,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Call site",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Lexical scope",
        displayOrder: 0,
        isCorrect: true,
      },
      {
        choiceText: "Global object always",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Prototype",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: ["Backend Engineer", "Node.js Developer"],
  },
  {
    category: "JavaScript",
    title: "Object.freeze #19",
    question: "What does Object.freeze do?",
    difficultyLabel: "MEDIUM",
    type: "CHOICE",
    explanation: "Freeze is shallow.",
    estimatedTimeSeconds: 60,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 4,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Deletes properties",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Prevents modifications",
        displayOrder: 0,

        isCorrect: true,
      },
      {
        choiceText: "Makes deep immutable",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Changes prototype",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: ["Full Stack Developer", "TypeScript Developer"],
  },
  {
    category: "JavaScript",
    title: "Debounce #20",
    question: "When is debouncing useful?",
    difficultyLabel: "MEDIUM",
    type: "CHOICE",
    explanation: "Debouncing limits rapid invocations.",
    estimatedTimeSeconds: 60,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 4,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Continuous animation",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Search input",
        displayOrder: 0,
        isCorrect: true,
      },
      {
        choiceText: "Sorting arrays",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "JSON parsing",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: [
      "Software Engineer",
      "Frontend Engineer",
      "Full Stack Developer",
    ],
  },
  {
    category: "JavaScript",
    title: "Block Scope with let #21",
    question:
      "A developer replaces var with let inside a loop. What is the primary benefit?",
    difficultyLabel: "EASY",
    type: "CHOICE",
    explanation: "let is block-scoped, reducing accidental leakage.",
    estimatedTimeSeconds: 45,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 2,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Block-scoped variables",
        displayOrder: 0,

        isCorrect: true,
      },
      {
        choiceText: "Automatic deep immutability",
        displayOrder: 0,

        isCorrect: false,
      },
      {
        choiceText: "Faster execution in all engines",
        displayOrder: 0,

        isCorrect: false,
      },
      {
        choiceText: "Variables become global",
        displayOrder: 0,

        isCorrect: false,
      },
    ],
    jobTitles: ["Software Engineer", "JavaScript Developer"],
  },
  {
    category: "JavaScript",
    title: "Array.map #22",
    question: "Which method creates a new array by transforming every element?",
    difficultyLabel: "EASY",
    type: "CHOICE",
    explanation: "map returns a new transformed array.",
    estimatedTimeSeconds: 45,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 2,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "filter",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "reduce",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "map",
        displayOrder: 0,
        isCorrect: true,
      },
      {
        choiceText: "find",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: ["Frontend Engineer", "React Developer"],
  },
  {
    category: "JavaScript",
    title: "Promise.all #23",
    question: "When does Promise.all reject?",
    difficultyLabel: "MEDIUM",
    type: "CHOICE",
    explanation: "It rejects immediately after the first rejection.",
    estimatedTimeSeconds: 60,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 4,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "When any promise rejects",
        displayOrder: 0,

        isCorrect: true,
      },
      {
        choiceText: "Only when all reject",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Never",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "After timeout",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: ["Backend Engineer", "Node.js Developer"],
  },
  {
    category: "JavaScript",
    title: "Optional Chaining #24",
    question: "What does obj?.user?.name return when user is undefined?",
    difficultyLabel: "EASY",
    type: "CHOICE",
    explanation: "Optional chaining safely returns undefined.",
    estimatedTimeSeconds: 45,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 2,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Throws TypeError",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "undefined",
        displayOrder: 0,
        isCorrect: true,
      },
      {
        choiceText: "null",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "''",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: ["Full Stack Developer", "TypeScript Developer"],
  },
  {
    category: "JavaScript",
    title: "Event Loop #25",
    question: "Which queue has higher priority after synchronous code?",
    difficultyLabel: "HARD",
    type: "CHOICE",
    explanation: "Microtasks run before macrotasks.",
    estimatedTimeSeconds: 90,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 6,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Timer queue",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Microtask queue",
        displayOrder: 0,
        isCorrect: true,
      },
      {
        choiceText: "Render queue",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Network queue",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: [
      "Software Engineer",
      "Frontend Engineer",
      "Full Stack Developer",
    ],
  },
  {
    category: "JavaScript",
    title: "Node Streams #26",
    question: "Why use streams for large files?",
    difficultyLabel: "MEDIUM",
    type: "CHOICE",
    explanation: "Streams process data incrementally.",
    estimatedTimeSeconds: 60,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 4,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Lower memory usage",
        displayOrder: 0,
        isCorrect: true,
      },
      {
        choiceText: "Automatic compression",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Faster CPU",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Parallel threads",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: ["Software Engineer", "JavaScript Developer"],
  },
  {
    category: "JavaScript",
    title: "Closures #27",
    question:
      "A returned function accesses outer variables after return. This is enabled by?",
    difficultyLabel: "MEDIUM",
    type: "CHOICE",
    explanation: "Closures preserve lexical environment.",
    estimatedTimeSeconds: 60,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 4,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Inheritance",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Closure",
        displayOrder: 0,
        isCorrect: true,
      },
      {
        choiceText: "Prototype",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Currying",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: ["Frontend Engineer", "React Developer"],
  },
  {
    category: "JavaScript",
    title: "this #28",
    question: "In an arrow function, this is determined by?",
    difficultyLabel: "MEDIUM",
    type: "CHOICE",
    explanation: "Arrow functions don't bind their own this.",
    estimatedTimeSeconds: 60,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 4,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Call site",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Lexical scope",
        displayOrder: 0,
        isCorrect: true,
      },
      {
        choiceText: "Global object always",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Prototype",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: ["Backend Engineer", "Node.js Developer"],
  },
  {
    category: "JavaScript",
    title: "Object.freeze #29",
    question: "What does Object.freeze do?",
    difficultyLabel: "MEDIUM",
    type: "CHOICE",
    explanation: "Freeze is shallow.",
    estimatedTimeSeconds: 60,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 4,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Deletes properties",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Prevents modifications",
        displayOrder: 0,

        isCorrect: true,
      },
      {
        choiceText: "Makes deep immutable",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Changes prototype",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: ["Full Stack Developer", "TypeScript Developer"],
  },
  {
    category: "JavaScript",
    title: "Debounce #30",
    question: "When is debouncing useful?",
    difficultyLabel: "MEDIUM",
    type: "CHOICE",
    explanation: "Debouncing limits rapid invocations.",
    estimatedTimeSeconds: 60,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 4,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Continuous animation",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Search input",
        displayOrder: 0,
        isCorrect: true,
      },
      {
        choiceText: "Sorting arrays",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "JSON parsing",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: [
      "Software Engineer",
      "Frontend Engineer",
      "Full Stack Developer",
    ],
  },
  {
    category: "JavaScript",
    title: "Block Scope with let #31",
    question:
      "A developer replaces var with let inside a loop. What is the primary benefit?",
    difficultyLabel: "EASY",
    type: "CHOICE",
    explanation: "let is block-scoped, reducing accidental leakage.",
    estimatedTimeSeconds: 45,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 2,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Block-scoped variables",
        displayOrder: 0,

        isCorrect: true,
      },
      {
        choiceText: "Automatic deep immutability",
        displayOrder: 0,

        isCorrect: false,
      },
      {
        choiceText: "Faster execution in all engines",
        displayOrder: 0,

        isCorrect: false,
      },
      {
        choiceText: "Variables become global",
        displayOrder: 0,

        isCorrect: false,
      },
    ],
    jobTitles: ["Software Engineer", "JavaScript Developer"],
  },
  {
    category: "JavaScript",
    title: "Array.map #32",
    question: "Which method creates a new array by transforming every element?",
    difficultyLabel: "EASY",
    type: "CHOICE",
    explanation: "map returns a new transformed array.",
    estimatedTimeSeconds: 45,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 2,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "filter",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "reduce",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "map",
        displayOrder: 0,
        isCorrect: true,
      },
      {
        choiceText: "find",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: ["Frontend Engineer", "React Developer"],
  },
  {
    category: "JavaScript",
    title: "Promise.all #33",
    question: "When does Promise.all reject?",
    difficultyLabel: "MEDIUM",
    type: "CHOICE",
    explanation: "It rejects immediately after the first rejection.",
    estimatedTimeSeconds: 60,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 4,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "When any promise rejects",
        displayOrder: 0,

        isCorrect: true,
      },
      {
        choiceText: "Only when all reject",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Never",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "After timeout",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: ["Backend Engineer", "Node.js Developer"],
  },
  {
    category: "JavaScript",
    title: "Optional Chaining #34",
    question: "What does obj?.user?.name return when user is undefined?",
    difficultyLabel: "EASY",
    type: "CHOICE",
    explanation: "Optional chaining safely returns undefined.",
    estimatedTimeSeconds: 45,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 2,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Throws TypeError",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "undefined",
        displayOrder: 0,
        isCorrect: true,
      },
      {
        choiceText: "null",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "''",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: ["Full Stack Developer", "TypeScript Developer"],
  },
  {
    category: "JavaScript",
    title: "Event Loop #35",
    question: "Which queue has higher priority after synchronous code?",
    difficultyLabel: "HARD",
    type: "CHOICE",
    explanation: "Microtasks run before macrotasks.",
    estimatedTimeSeconds: 90,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 6,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Timer queue",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Microtask queue",
        displayOrder: 0,
        isCorrect: true,
      },
      {
        choiceText: "Render queue",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Network queue",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: [
      "Software Engineer",
      "Frontend Engineer",
      "Full Stack Developer",
    ],
  },
  {
    category: "JavaScript",
    title: "Node Streams #36",
    question: "Why use streams for large files?",
    difficultyLabel: "MEDIUM",
    type: "CHOICE",
    explanation: "Streams process data incrementally.",
    estimatedTimeSeconds: 60,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 4,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Lower memory usage",
        displayOrder: 0,
        isCorrect: true,
      },
      {
        choiceText: "Automatic compression",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Faster CPU",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Parallel threads",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: ["Software Engineer", "JavaScript Developer"],
  },
  {
    category: "JavaScript",
    title: "Closures #37",
    question:
      "A returned function accesses outer variables after return. This is enabled by?",
    difficultyLabel: "MEDIUM",
    type: "CHOICE",
    explanation: "Closures preserve lexical environment.",
    estimatedTimeSeconds: 60,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 4,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Inheritance",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Closure",
        displayOrder: 0,
        isCorrect: true,
      },
      {
        choiceText: "Prototype",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Currying",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: ["Frontend Engineer", "React Developer"],
  },
  {
    category: "JavaScript",
    title: "this #38",
    question: "In an arrow function, this is determined by?",
    difficultyLabel: "MEDIUM",
    type: "CHOICE",
    explanation: "Arrow functions don't bind their own this.",
    estimatedTimeSeconds: 60,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 4,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Call site",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Lexical scope",
        displayOrder: 0,
        isCorrect: true,
      },
      {
        choiceText: "Global object always",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Prototype",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: ["Backend Engineer", "Node.js Developer"],
  },
  {
    category: "JavaScript",
    title: "Object.freeze #39",
    question: "What does Object.freeze do?",
    difficultyLabel: "MEDIUM",
    type: "CHOICE",
    explanation: "Freeze is shallow.",
    estimatedTimeSeconds: 60,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 4,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Deletes properties",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Prevents modifications",
        displayOrder: 0,

        isCorrect: true,
      },
      {
        choiceText: "Makes deep immutable",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Changes prototype",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: ["Full Stack Developer", "TypeScript Developer"],
  },
  {
    category: "JavaScript",
    title: "Debounce #40",
    question: "When is debouncing useful?",
    difficultyLabel: "MEDIUM",
    type: "CHOICE",
    explanation: "Debouncing limits rapid invocations.",
    estimatedTimeSeconds: 60,
    questionData: {
      context: "Software engineering recruitment scenario.",
      shuffleChoices: true,
      multipleSelection: false,
    },
    version: 1,
    points: 4,
    isPublic: true,
    isActive: true,
    createdBy: "system",
    choices: [
      {
        choiceText: "Continuous animation",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "Search input",
        displayOrder: 0,
        isCorrect: true,
      },
      {
        choiceText: "Sorting arrays",
        displayOrder: 0,
        isCorrect: false,
      },
      {
        choiceText: "JSON parsing",
        displayOrder: 0,
        isCorrect: false,
      },
    ],
    jobTitles: [
      "Software Engineer",
      "Frontend Engineer",
      "Full Stack Developer",
    ],
  },
];
